package in.testpress.exam.models.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "REVIEW_ANSWER".
 */
@Entity
public class ReviewAnswer {

    @Id
    private Long id;
    private String textHtml;
    private Boolean isCorrect;
    private Long questionId;

    @Generated
    public ReviewAnswer() {
    }

    public ReviewAnswer(Long id) {
        this.id = id;
    }

    @Generated
    public ReviewAnswer(Long id, String textHtml, Boolean isCorrect, Long questionId) {
        this.id = id;
        this.textHtml = textHtml;
        this.isCorrect = isCorrect;
        this.questionId = questionId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTextHtml() {
        return textHtml;
    }

    public void setTextHtml(String textHtml) {
        this.textHtml = textHtml;
    }

    public Boolean getIsCorrect() {
        return isCorrect;
    }

    public void setIsCorrect(Boolean isCorrect) {
        this.isCorrect = isCorrect;
    }

    public Long getQuestionId() {
        return questionId;
    }

    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

}
