language: android

sudo: required
dist: precise

jdk: oraclejdk8

android:
 components:
    # latest version of the tools
    - tools
    - platform-tools

    # build tools version
    - build-tools-23.0.3

    # The SDK Version
    - android-23
    - android-24

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

    # Emulator
    - sys-img-armeabi-v7a-android-23

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &