language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=24
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)

android:
 components:
    # latest version of the tools
    - tools
    - platform-tools

    # build tools version
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK Version
    - android-$ANDROID_API_LEVEL

    # For Google APIs
    - addon-google_apis-google-$ANDROID_API_LEVEL

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

script:
    - ./gradlew build check