language: android

jdk: oraclejdk8

android:
 components:
    # latest version of the tools
    - tools
    - platform-tools

    # build tools version
    - build-tools-23.0.3

    # The SDK Version
    - android-23
    - android-24

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
