package in.testpress.models.greendao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ANSWER".
*/
public class AnswerDao extends AbstractDao<Answer, Long> {

    public static final String TABLENAME = "ANSWER";

    /**
     * Properties of entity Answer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property TextHtml = new Property(1, String.class, "textHtml", false, "TEXT_HTML");
        public final static Property IsCorrect = new Property(2, Boolean.class, "isCorrect", false, "IS_CORRECT");
        public final static Property Marks = new Property(3, String.class, "marks", false, "MARKS");
        public final static Property QuestionId = new Property(4, Long.class, "questionId", false, "QUESTION_ID");
    }

    private Query<Answer> question_AnswersQuery;

    public AnswerDao(DaoConfig config) {
        super(config);
    }
    
    public AnswerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ANSWER\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TEXT_HTML\" TEXT," + // 1: textHtml
                "\"IS_CORRECT\" INTEGER," + // 2: isCorrect
                "\"MARKS\" TEXT," + // 3: marks
                "\"QUESTION_ID\" INTEGER);"); // 4: questionId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ANSWER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Answer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String textHtml = entity.getTextHtml();
        if (textHtml != null) {
            stmt.bindString(2, textHtml);
        }
 
        Boolean isCorrect = entity.getIsCorrect();
        if (isCorrect != null) {
            stmt.bindLong(3, isCorrect ? 1L: 0L);
        }
 
        String marks = entity.getMarks();
        if (marks != null) {
            stmt.bindString(4, marks);
        }
 
        Long questionId = entity.getQuestionId();
        if (questionId != null) {
            stmt.bindLong(5, questionId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Answer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String textHtml = entity.getTextHtml();
        if (textHtml != null) {
            stmt.bindString(2, textHtml);
        }
 
        Boolean isCorrect = entity.getIsCorrect();
        if (isCorrect != null) {
            stmt.bindLong(3, isCorrect ? 1L: 0L);
        }
 
        String marks = entity.getMarks();
        if (marks != null) {
            stmt.bindString(4, marks);
        }
 
        Long questionId = entity.getQuestionId();
        if (questionId != null) {
            stmt.bindLong(5, questionId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Answer readEntity(Cursor cursor, int offset) {
        Answer entity = new Answer( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // textHtml
            cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0, // isCorrect
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // marks
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // questionId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Answer entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTextHtml(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIsCorrect(cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0);
        entity.setMarks(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setQuestionId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Answer entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Answer entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Answer entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "answers" to-many relationship of Question. */
    public List<Answer> _queryQuestion_Answers(Long questionId) {
        synchronized (this) {
            if (question_AnswersQuery == null) {
                QueryBuilder<Answer> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.QuestionId.eq(null));
                question_AnswersQuery = queryBuilder.build();
            }
        }
        Query<Answer> query = question_AnswersQuery.forCurrentThread();
        query.setParameter(0, questionId);
        return query.list();
    }

}
