package in.testpress.models.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONTENT_TYPE".
*/
public class ContentTypeDao extends AbstractDao<ContentType, Long> {

    public static final String TABLENAME = "CONTENT_TYPE";

    /**
     * Properties of entity ContentType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Model = new Property(1, String.class, "model", false, "MODEL");
        public final static Property AppLabel = new Property(2, String.class, "appLabel", false, "APP_LABEL");
    }


    public ContentTypeDao(DaoConfig config) {
        super(config);
    }
    
    public ContentTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONTENT_TYPE\" (" + //
                "\"ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MODEL\" TEXT," + // 1: model
                "\"APP_LABEL\" TEXT);"); // 2: appLabel
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_CONTENT_TYPE_MODEL_APP_LABEL ON CONTENT_TYPE" +
                " (\"MODEL\",\"APP_LABEL\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONTENT_TYPE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ContentType entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String model = entity.getModel();
        if (model != null) {
            stmt.bindString(2, model);
        }
 
        String appLabel = entity.getAppLabel();
        if (appLabel != null) {
            stmt.bindString(3, appLabel);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ContentType entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String model = entity.getModel();
        if (model != null) {
            stmt.bindString(2, model);
        }
 
        String appLabel = entity.getAppLabel();
        if (appLabel != null) {
            stmt.bindString(3, appLabel);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ContentType readEntity(Cursor cursor, int offset) {
        ContentType entity = new ContentType( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // model
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // appLabel
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ContentType entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setModel(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAppLabel(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ContentType entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ContentType entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ContentType entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
