package in.testpress.models.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COURSE_ATTEMPT".
*/
public class CourseAttemptDao extends AbstractDao<CourseAttempt, Long> {

    public static final String TABLENAME = "COURSE_ATTEMPT";

    /**
     * Properties of entity CourseAttempt.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Type = new Property(1, String.class, "type", false, "TYPE");
        public final static Property ObjectId = new Property(2, Integer.class, "objectId", false, "OBJECT_ID");
        public final static Property ObjectUrl = new Property(3, String.class, "objectUrl", false, "OBJECT_URL");
        public final static Property Trophies = new Property(4, String.class, "trophies", false, "TROPHIES");
        public final static Property CourseContentId = new Property(5, Long.class, "courseContentId", false, "COURSE_CONTENT_ID");
        public final static Property AttemptId = new Property(6, Long.class, "attemptId", false, "ATTEMPT_ID");
    }

    private DaoSession daoSession;


    public CourseAttemptDao(DaoConfig config) {
        super(config);
    }
    
    public CourseAttemptDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COURSE_ATTEMPT\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TYPE\" TEXT," + // 1: type
                "\"OBJECT_ID\" INTEGER," + // 2: objectId
                "\"OBJECT_URL\" TEXT," + // 3: objectUrl
                "\"TROPHIES\" TEXT," + // 4: trophies
                "\"COURSE_CONTENT_ID\" INTEGER," + // 5: courseContentId
                "\"ATTEMPT_ID\" INTEGER);"); // 6: attemptId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COURSE_ATTEMPT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CourseAttempt entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(2, type);
        }
 
        Integer objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindLong(3, objectId);
        }
 
        String objectUrl = entity.getObjectUrl();
        if (objectUrl != null) {
            stmt.bindString(4, objectUrl);
        }
 
        String trophies = entity.getTrophies();
        if (trophies != null) {
            stmt.bindString(5, trophies);
        }
 
        Long courseContentId = entity.getCourseContentId();
        if (courseContentId != null) {
            stmt.bindLong(6, courseContentId);
        }
 
        Long attemptId = entity.getAttemptId();
        if (attemptId != null) {
            stmt.bindLong(7, attemptId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CourseAttempt entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(2, type);
        }
 
        Integer objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindLong(3, objectId);
        }
 
        String objectUrl = entity.getObjectUrl();
        if (objectUrl != null) {
            stmt.bindString(4, objectUrl);
        }
 
        String trophies = entity.getTrophies();
        if (trophies != null) {
            stmt.bindString(5, trophies);
        }
 
        Long courseContentId = entity.getCourseContentId();
        if (courseContentId != null) {
            stmt.bindLong(6, courseContentId);
        }
 
        Long attemptId = entity.getAttemptId();
        if (attemptId != null) {
            stmt.bindLong(7, attemptId);
        }
    }

    @Override
    protected final void attachEntity(CourseAttempt entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CourseAttempt readEntity(Cursor cursor, int offset) {
        CourseAttempt entity = new CourseAttempt( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // type
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // objectId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // objectUrl
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // trophies
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // courseContentId
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6) // attemptId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CourseAttempt entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setObjectId(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setObjectUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTrophies(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCourseContentId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setAttemptId(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CourseAttempt entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CourseAttempt entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CourseAttempt entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCourseContentDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getAttemptDao().getAllColumns());
            builder.append(" FROM COURSE_ATTEMPT T");
            builder.append(" LEFT JOIN COURSE_CONTENT T0 ON T.\"COURSE_CONTENT_ID\"=T0.\"ID\"");
            builder.append(" LEFT JOIN ATTEMPT T1 ON T.\"ATTEMPT_ID\"=T1.\"ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected CourseAttempt loadCurrentDeep(Cursor cursor, boolean lock) {
        CourseAttempt entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        CourseContent chapterContent = loadCurrentOther(daoSession.getCourseContentDao(), cursor, offset);
        entity.setChapterContent(chapterContent);
        offset += daoSession.getCourseContentDao().getAllColumns().length;

        Attempt assessment = loadCurrentOther(daoSession.getAttemptDao(), cursor, offset);
        entity.setAssessment(assessment);

        return entity;    
    }

    public CourseAttempt loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<CourseAttempt> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<CourseAttempt> list = new ArrayList<CourseAttempt>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<CourseAttempt> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<CourseAttempt> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
