package in.testpress.models.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import in.testpress.models.greendao.ReviewAttempt;
import in.testpress.models.greendao.ReviewItem;
import in.testpress.models.greendao.ReviewQuestion;
import in.testpress.models.greendao.ReviewAnswer;
import in.testpress.models.greendao.ReviewQuestionTranslation;
import in.testpress.models.greendao.ReviewAnswerTranslation;
import in.testpress.models.greendao.SelectedAnswer;
import in.testpress.models.greendao.Course;
import in.testpress.models.greendao.Chapter;
import in.testpress.models.greendao.Video;
import in.testpress.models.greendao.Attachment;
import in.testpress.models.greendao.Exam;
import in.testpress.models.greendao.Language;
import in.testpress.models.greendao.Content;
import in.testpress.models.greendao.HtmlContent;
import in.testpress.models.greendao.CourseAttempt;
import in.testpress.models.greendao.Attempt;

import in.testpress.models.greendao.ReviewAttemptDao;
import in.testpress.models.greendao.ReviewItemDao;
import in.testpress.models.greendao.ReviewQuestionDao;
import in.testpress.models.greendao.ReviewAnswerDao;
import in.testpress.models.greendao.ReviewQuestionTranslationDao;
import in.testpress.models.greendao.ReviewAnswerTranslationDao;
import in.testpress.models.greendao.SelectedAnswerDao;
import in.testpress.models.greendao.CourseDao;
import in.testpress.models.greendao.ChapterDao;
import in.testpress.models.greendao.VideoDao;
import in.testpress.models.greendao.AttachmentDao;
import in.testpress.models.greendao.ExamDao;
import in.testpress.models.greendao.LanguageDao;
import in.testpress.models.greendao.ContentDao;
import in.testpress.models.greendao.HtmlContentDao;
import in.testpress.models.greendao.CourseAttemptDao;
import in.testpress.models.greendao.AttemptDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig reviewAttemptDaoConfig;
    private final DaoConfig reviewItemDaoConfig;
    private final DaoConfig reviewQuestionDaoConfig;
    private final DaoConfig reviewAnswerDaoConfig;
    private final DaoConfig reviewQuestionTranslationDaoConfig;
    private final DaoConfig reviewAnswerTranslationDaoConfig;
    private final DaoConfig selectedAnswerDaoConfig;
    private final DaoConfig courseDaoConfig;
    private final DaoConfig chapterDaoConfig;
    private final DaoConfig videoDaoConfig;
    private final DaoConfig attachmentDaoConfig;
    private final DaoConfig examDaoConfig;
    private final DaoConfig languageDaoConfig;
    private final DaoConfig contentDaoConfig;
    private final DaoConfig htmlContentDaoConfig;
    private final DaoConfig courseAttemptDaoConfig;
    private final DaoConfig attemptDaoConfig;

    private final ReviewAttemptDao reviewAttemptDao;
    private final ReviewItemDao reviewItemDao;
    private final ReviewQuestionDao reviewQuestionDao;
    private final ReviewAnswerDao reviewAnswerDao;
    private final ReviewQuestionTranslationDao reviewQuestionTranslationDao;
    private final ReviewAnswerTranslationDao reviewAnswerTranslationDao;
    private final SelectedAnswerDao selectedAnswerDao;
    private final CourseDao courseDao;
    private final ChapterDao chapterDao;
    private final VideoDao videoDao;
    private final AttachmentDao attachmentDao;
    private final ExamDao examDao;
    private final LanguageDao languageDao;
    private final ContentDao contentDao;
    private final HtmlContentDao htmlContentDao;
    private final CourseAttemptDao courseAttemptDao;
    private final AttemptDao attemptDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        reviewAttemptDaoConfig = daoConfigMap.get(ReviewAttemptDao.class).clone();
        reviewAttemptDaoConfig.initIdentityScope(type);

        reviewItemDaoConfig = daoConfigMap.get(ReviewItemDao.class).clone();
        reviewItemDaoConfig.initIdentityScope(type);

        reviewQuestionDaoConfig = daoConfigMap.get(ReviewQuestionDao.class).clone();
        reviewQuestionDaoConfig.initIdentityScope(type);

        reviewAnswerDaoConfig = daoConfigMap.get(ReviewAnswerDao.class).clone();
        reviewAnswerDaoConfig.initIdentityScope(type);

        reviewQuestionTranslationDaoConfig = daoConfigMap.get(ReviewQuestionTranslationDao.class).clone();
        reviewQuestionTranslationDaoConfig.initIdentityScope(type);

        reviewAnswerTranslationDaoConfig = daoConfigMap.get(ReviewAnswerTranslationDao.class).clone();
        reviewAnswerTranslationDaoConfig.initIdentityScope(type);

        selectedAnswerDaoConfig = daoConfigMap.get(SelectedAnswerDao.class).clone();
        selectedAnswerDaoConfig.initIdentityScope(type);

        courseDaoConfig = daoConfigMap.get(CourseDao.class).clone();
        courseDaoConfig.initIdentityScope(type);

        chapterDaoConfig = daoConfigMap.get(ChapterDao.class).clone();
        chapterDaoConfig.initIdentityScope(type);

        videoDaoConfig = daoConfigMap.get(VideoDao.class).clone();
        videoDaoConfig.initIdentityScope(type);

        attachmentDaoConfig = daoConfigMap.get(AttachmentDao.class).clone();
        attachmentDaoConfig.initIdentityScope(type);

        examDaoConfig = daoConfigMap.get(ExamDao.class).clone();
        examDaoConfig.initIdentityScope(type);

        languageDaoConfig = daoConfigMap.get(LanguageDao.class).clone();
        languageDaoConfig.initIdentityScope(type);

        contentDaoConfig = daoConfigMap.get(ContentDao.class).clone();
        contentDaoConfig.initIdentityScope(type);

        htmlContentDaoConfig = daoConfigMap.get(HtmlContentDao.class).clone();
        htmlContentDaoConfig.initIdentityScope(type);

        courseAttemptDaoConfig = daoConfigMap.get(CourseAttemptDao.class).clone();
        courseAttemptDaoConfig.initIdentityScope(type);

        attemptDaoConfig = daoConfigMap.get(AttemptDao.class).clone();
        attemptDaoConfig.initIdentityScope(type);

        reviewAttemptDao = new ReviewAttemptDao(reviewAttemptDaoConfig, this);
        reviewItemDao = new ReviewItemDao(reviewItemDaoConfig, this);
        reviewQuestionDao = new ReviewQuestionDao(reviewQuestionDaoConfig, this);
        reviewAnswerDao = new ReviewAnswerDao(reviewAnswerDaoConfig, this);
        reviewQuestionTranslationDao = new ReviewQuestionTranslationDao(reviewQuestionTranslationDaoConfig, this);
        reviewAnswerTranslationDao = new ReviewAnswerTranslationDao(reviewAnswerTranslationDaoConfig, this);
        selectedAnswerDao = new SelectedAnswerDao(selectedAnswerDaoConfig, this);
        courseDao = new CourseDao(courseDaoConfig, this);
        chapterDao = new ChapterDao(chapterDaoConfig, this);
        videoDao = new VideoDao(videoDaoConfig, this);
        attachmentDao = new AttachmentDao(attachmentDaoConfig, this);
        examDao = new ExamDao(examDaoConfig, this);
        languageDao = new LanguageDao(languageDaoConfig, this);
        contentDao = new ContentDao(contentDaoConfig, this);
        htmlContentDao = new HtmlContentDao(htmlContentDaoConfig, this);
        courseAttemptDao = new CourseAttemptDao(courseAttemptDaoConfig, this);
        attemptDao = new AttemptDao(attemptDaoConfig, this);

        registerDao(ReviewAttempt.class, reviewAttemptDao);
        registerDao(ReviewItem.class, reviewItemDao);
        registerDao(ReviewQuestion.class, reviewQuestionDao);
        registerDao(ReviewAnswer.class, reviewAnswerDao);
        registerDao(ReviewQuestionTranslation.class, reviewQuestionTranslationDao);
        registerDao(ReviewAnswerTranslation.class, reviewAnswerTranslationDao);
        registerDao(SelectedAnswer.class, selectedAnswerDao);
        registerDao(Course.class, courseDao);
        registerDao(Chapter.class, chapterDao);
        registerDao(Video.class, videoDao);
        registerDao(Attachment.class, attachmentDao);
        registerDao(Exam.class, examDao);
        registerDao(Language.class, languageDao);
        registerDao(Content.class, contentDao);
        registerDao(HtmlContent.class, htmlContentDao);
        registerDao(CourseAttempt.class, courseAttemptDao);
        registerDao(Attempt.class, attemptDao);
    }
    
    public void clear() {
        reviewAttemptDaoConfig.clearIdentityScope();
        reviewItemDaoConfig.clearIdentityScope();
        reviewQuestionDaoConfig.clearIdentityScope();
        reviewAnswerDaoConfig.clearIdentityScope();
        reviewQuestionTranslationDaoConfig.clearIdentityScope();
        reviewAnswerTranslationDaoConfig.clearIdentityScope();
        selectedAnswerDaoConfig.clearIdentityScope();
        courseDaoConfig.clearIdentityScope();
        chapterDaoConfig.clearIdentityScope();
        videoDaoConfig.clearIdentityScope();
        attachmentDaoConfig.clearIdentityScope();
        examDaoConfig.clearIdentityScope();
        languageDaoConfig.clearIdentityScope();
        contentDaoConfig.clearIdentityScope();
        htmlContentDaoConfig.clearIdentityScope();
        courseAttemptDaoConfig.clearIdentityScope();
        attemptDaoConfig.clearIdentityScope();
    }

    public ReviewAttemptDao getReviewAttemptDao() {
        return reviewAttemptDao;
    }

    public ReviewItemDao getReviewItemDao() {
        return reviewItemDao;
    }

    public ReviewQuestionDao getReviewQuestionDao() {
        return reviewQuestionDao;
    }

    public ReviewAnswerDao getReviewAnswerDao() {
        return reviewAnswerDao;
    }

    public ReviewQuestionTranslationDao getReviewQuestionTranslationDao() {
        return reviewQuestionTranslationDao;
    }

    public ReviewAnswerTranslationDao getReviewAnswerTranslationDao() {
        return reviewAnswerTranslationDao;
    }

    public SelectedAnswerDao getSelectedAnswerDao() {
        return selectedAnswerDao;
    }

    public CourseDao getCourseDao() {
        return courseDao;
    }

    public ChapterDao getChapterDao() {
        return chapterDao;
    }

    public VideoDao getVideoDao() {
        return videoDao;
    }

    public AttachmentDao getAttachmentDao() {
        return attachmentDao;
    }

    public ExamDao getExamDao() {
        return examDao;
    }

    public LanguageDao getLanguageDao() {
        return languageDao;
    }

    public ContentDao getContentDao() {
        return contentDao;
    }

    public HtmlContentDao getHtmlContentDao() {
        return htmlContentDao;
    }

    public CourseAttemptDao getCourseAttemptDao() {
        return courseAttemptDao;
    }

    public AttemptDao getAttemptDao() {
        return attemptDao;
    }

}
