package in.testpress.models.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "HTML_CONTENT".
 */
@Entity
public class HtmlContent {
    private String title;
    private String textHtml;
    private String sourceUrl;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public HtmlContent() {
    }

    @Generated
    public HtmlContent(String title, String textHtml, String sourceUrl) {
        this.title = title;
        this.textHtml = textHtml;
        this.sourceUrl = sourceUrl;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTextHtml() {
        return textHtml;
    }

    public void setTextHtml(String textHtml) {
        this.textHtml = textHtml;
    }

    public String getSourceUrl() {
        return sourceUrl;
    }

    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
