package in.testpress.models.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INSTALLMENT_PLAN".
*/
public class InstallmentPlanDao extends AbstractDao<InstallmentPlan, Long> {

    public static final String TABLENAME = "INSTALLMENT_PLAN";

    /**
     * Properties of entity InstallmentPlan.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Price = new Property(1, String.class, "price", false, "PRICE");
        public final static Property NumberOfInstallments = new Property(2, Integer.class, "numberOfInstallments", false, "NUMBER_OF_INSTALLMENTS");
        public final static Property Period = new Property(3, Integer.class, "period", false, "PERIOD");
        public final static Property DisplayName = new Property(4, String.class, "displayName", false, "DISPLAY_NAME");
    }


    public InstallmentPlanDao(DaoConfig config) {
        super(config);
    }
    
    public InstallmentPlanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INSTALLMENT_PLAN\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PRICE\" TEXT," + // 1: price
                "\"NUMBER_OF_INSTALLMENTS\" INTEGER," + // 2: numberOfInstallments
                "\"PERIOD\" INTEGER," + // 3: period
                "\"DISPLAY_NAME\" TEXT);"); // 4: displayName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INSTALLMENT_PLAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, InstallmentPlan entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(2, price);
        }
 
        Integer numberOfInstallments = entity.getNumberOfInstallments();
        if (numberOfInstallments != null) {
            stmt.bindLong(3, numberOfInstallments);
        }
 
        Integer period = entity.getPeriod();
        if (period != null) {
            stmt.bindLong(4, period);
        }
 
        String displayName = entity.getDisplayName();
        if (displayName != null) {
            stmt.bindString(5, displayName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, InstallmentPlan entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(2, price);
        }
 
        Integer numberOfInstallments = entity.getNumberOfInstallments();
        if (numberOfInstallments != null) {
            stmt.bindLong(3, numberOfInstallments);
        }
 
        Integer period = entity.getPeriod();
        if (period != null) {
            stmt.bindLong(4, period);
        }
 
        String displayName = entity.getDisplayName();
        if (displayName != null) {
            stmt.bindString(5, displayName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public InstallmentPlan readEntity(Cursor cursor, int offset) {
        InstallmentPlan entity = new InstallmentPlan( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // price
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // numberOfInstallments
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // period
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // displayName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, InstallmentPlan entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPrice(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNumberOfInstallments(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setPeriod(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setDisplayName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(InstallmentPlan entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(InstallmentPlan entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(InstallmentPlan entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
