package in.testpress.models.greendao;

import org.greenrobot.greendao.annotation.*;

import in.testpress.models.greendao.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "INSTALLMENT".
 */
@Entity(active = true)
public class Installment {

    @Id
    private Long id;
    private Integer order;
    private String price;
    private Boolean isPaid;
    private String paidOn;
    private Boolean isCurrentInstallment;
    private String dueDate;
    private Long installmentPlanId;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient InstallmentDao myDao;

    @ToOne(joinProperty = "installmentPlanId")
    private InstallmentPlan installmentPlan;

    @Generated
    private transient Long installmentPlan__resolvedKey;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Installment() {
    }

    public Installment(Long id) {
        this.id = id;
    }

    @Generated
    public Installment(Long id, Integer order, String price, Boolean isPaid, String paidOn, Boolean isCurrentInstallment, String dueDate, Long installmentPlanId) {
        this.id = id;
        this.order = order;
        this.price = price;
        this.isPaid = isPaid;
        this.paidOn = paidOn;
        this.isCurrentInstallment = isCurrentInstallment;
        this.dueDate = dueDate;
        this.installmentPlanId = installmentPlanId;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getInstallmentDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public Boolean getIsPaid() {
        return isPaid;
    }

    public void setIsPaid(Boolean isPaid) {
        this.isPaid = isPaid;
    }

    public String getPaidOn() {
        return paidOn;
    }

    public void setPaidOn(String paidOn) {
        this.paidOn = paidOn;
    }

    public Boolean getIsCurrentInstallment() {
        return isCurrentInstallment;
    }

    public void setIsCurrentInstallment(Boolean isCurrentInstallment) {
        this.isCurrentInstallment = isCurrentInstallment;
    }

    public String getDueDate() {
        return dueDate;
    }

    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }

    public Long getInstallmentPlanId() {
        return installmentPlanId;
    }

    public void setInstallmentPlanId(Long installmentPlanId) {
        this.installmentPlanId = installmentPlanId;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public InstallmentPlan getInstallmentPlan() {
        Long __key = this.installmentPlanId;
        if (installmentPlan__resolvedKey == null || !installmentPlan__resolvedKey.equals(__key)) {
            __throwIfDetached();
            InstallmentPlanDao targetDao = daoSession.getInstallmentPlanDao();
            InstallmentPlan installmentPlanNew = targetDao.load(__key);
            synchronized (this) {
                installmentPlan = installmentPlanNew;
            	installmentPlan__resolvedKey = __key;
            }
        }
        return installmentPlan;
    }

    @Generated
    public void setInstallmentPlan(InstallmentPlan installmentPlan) {
        synchronized (this) {
            this.installmentPlan = installmentPlan;
            installmentPlanId = installmentPlan == null ? null : installmentPlan.getId();
            installmentPlan__resolvedKey = installmentPlanId;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
