package in.testpress.models.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "LANGUAGE".
 */
@Entity
public class Language {

    @Id(autoincrement = true)
    private Long id;
    private String code;
    private String title;
    private String exam_slug;

    @Generated
    public Language() {
    }

    public Language(Long id) {
        this.id = id;
    }

    @Generated
    public Language(Long id, String code, String title, String exam_slug) {
        this.id = id;
        this.code = code;
        this.title = title;
        this.exam_slug = exam_slug;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getExam_slug() {
        return exam_slug;
    }

    public void setExam_slug(String exam_slug) {
        this.exam_slug = exam_slug;
    }

    public Language(Language language) {
        code = language.getCode();
        title = language.getTitle();
    }
    public void update(Language language) {
        code = language.getCode();
        title = language.getTitle();
    }
}
