package in.testpress.models.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "LIVE_STREAM".
 */
@Entity
public class LiveStream {

    @Id
    private Long id;
    private String title;
    private String streamURL;
    private Integer duration;
    private String status;
    private Boolean showRecordedVideo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public LiveStream() {
    }

    public LiveStream(Long id) {
        this.id = id;
    }

    @Generated
    public LiveStream(Long id, String title, String streamURL, Integer duration, String status, Boolean showRecordedVideo) {
        this.id = id;
        this.title = title;
        this.streamURL = streamURL;
        this.duration = duration;
        this.status = status;
        this.showRecordedVideo = showRecordedVideo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getStreamURL() {
        return streamURL;
    }

    public void setStreamURL(String streamURL) {
        this.streamURL = streamURL;
    }

    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Boolean getShowRecordedVideo() {
        return showRecordedVideo;
    }

    public void setShowRecordedVideo(Boolean showRecordedVideo) {
        this.showRecordedVideo = showRecordedVideo;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
