package in.testpress.models.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "REVIEW_ANSWER_TRANSLATION".
 */
@Entity
public class ReviewAnswerTranslation {

    @Id(autoincrement = true)
    private Long translationAnswerId;
    private Long id;
    private String textHtml;
    private Boolean isCorrect;
    private Long questionTranslationId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ReviewAnswerTranslation() {
    }

    public ReviewAnswerTranslation(Long translationAnswerId) {
        this.translationAnswerId = translationAnswerId;
    }

    @Generated
    public ReviewAnswerTranslation(Long translationAnswerId, Long id, String textHtml, Boolean isCorrect, Long questionTranslationId) {
        this.translationAnswerId = translationAnswerId;
        this.id = id;
        this.textHtml = textHtml;
        this.isCorrect = isCorrect;
        this.questionTranslationId = questionTranslationId;
    }

    public Long getTranslationAnswerId() {
        return translationAnswerId;
    }

    public void setTranslationAnswerId(Long translationAnswerId) {
        this.translationAnswerId = translationAnswerId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTextHtml() {
        return textHtml;
    }

    public void setTextHtml(String textHtml) {
        this.textHtml = textHtml;
    }

    public Boolean getIsCorrect() {
        return isCorrect;
    }

    public void setIsCorrect(Boolean isCorrect) {
        this.isCorrect = isCorrect;
    }

    public Long getQuestionTranslationId() {
        return questionTranslationId;
    }

    public void setQuestionTranslationId(Long questionTranslationId) {
        this.questionTranslationId = questionTranslationId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
