package in.testpress.models.greendao;

import org.greenrobot.greendao.annotation.*;

import in.testpress.models.greendao.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "USER_INSTALLMENT_PLAN".
 */
@Entity(active = true)
public class UserInstallmentPlan {

    @Id
    private Long id;
    private String status;
    private Integer paidInstallmentCount;
    private Integer totalInstallments;
    private String nextDueAmount;
    private String nextDueDate;
    private String amountPaid;
    private String amountDue;
    private Boolean isCustomPlan;
    private Boolean isPaid;
    private Boolean isPartiallyPaid;
    private Boolean isOverdue;
    private Long installmentPlanId;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient UserInstallmentPlanDao myDao;

    @ToOne(joinProperty = "installmentPlanId")
    private InstallmentPlan installmentPlan;

    @Generated
    private transient Long installmentPlan__resolvedKey;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public UserInstallmentPlan() {
    }

    public UserInstallmentPlan(Long id) {
        this.id = id;
    }

    @Generated
    public UserInstallmentPlan(Long id, String status, Integer paidInstallmentCount, Integer totalInstallments, String nextDueAmount, String nextDueDate, String amountPaid, String amountDue, Boolean isCustomPlan, Boolean isPaid, Boolean isPartiallyPaid, Boolean isOverdue, Long installmentPlanId) {
        this.id = id;
        this.status = status;
        this.paidInstallmentCount = paidInstallmentCount;
        this.totalInstallments = totalInstallments;
        this.nextDueAmount = nextDueAmount;
        this.nextDueDate = nextDueDate;
        this.amountPaid = amountPaid;
        this.amountDue = amountDue;
        this.isCustomPlan = isCustomPlan;
        this.isPaid = isPaid;
        this.isPartiallyPaid = isPartiallyPaid;
        this.isOverdue = isOverdue;
        this.installmentPlanId = installmentPlanId;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getUserInstallmentPlanDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getPaidInstallmentCount() {
        return paidInstallmentCount;
    }

    public void setPaidInstallmentCount(Integer paidInstallmentCount) {
        this.paidInstallmentCount = paidInstallmentCount;
    }

    public Integer getTotalInstallments() {
        return totalInstallments;
    }

    public void setTotalInstallments(Integer totalInstallments) {
        this.totalInstallments = totalInstallments;
    }

    public String getNextDueAmount() {
        return nextDueAmount;
    }

    public void setNextDueAmount(String nextDueAmount) {
        this.nextDueAmount = nextDueAmount;
    }

    public String getNextDueDate() {
        return nextDueDate;
    }

    public void setNextDueDate(String nextDueDate) {
        this.nextDueDate = nextDueDate;
    }

    public String getAmountPaid() {
        return amountPaid;
    }

    public void setAmountPaid(String amountPaid) {
        this.amountPaid = amountPaid;
    }

    public String getAmountDue() {
        return amountDue;
    }

    public void setAmountDue(String amountDue) {
        this.amountDue = amountDue;
    }

    public Boolean getIsCustomPlan() {
        return isCustomPlan;
    }

    public void setIsCustomPlan(Boolean isCustomPlan) {
        this.isCustomPlan = isCustomPlan;
    }

    public Boolean getIsPaid() {
        return isPaid;
    }

    public void setIsPaid(Boolean isPaid) {
        this.isPaid = isPaid;
    }

    public Boolean getIsPartiallyPaid() {
        return isPartiallyPaid;
    }

    public void setIsPartiallyPaid(Boolean isPartiallyPaid) {
        this.isPartiallyPaid = isPartiallyPaid;
    }

    public Boolean getIsOverdue() {
        return isOverdue;
    }

    public void setIsOverdue(Boolean isOverdue) {
        this.isOverdue = isOverdue;
    }

    public Long getInstallmentPlanId() {
        return installmentPlanId;
    }

    public void setInstallmentPlanId(Long installmentPlanId) {
        this.installmentPlanId = installmentPlanId;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public InstallmentPlan getInstallmentPlan() {
        Long __key = this.installmentPlanId;
        if (installmentPlan__resolvedKey == null || !installmentPlan__resolvedKey.equals(__key)) {
            __throwIfDetached();
            InstallmentPlanDao targetDao = daoSession.getInstallmentPlanDao();
            InstallmentPlan installmentPlanNew = targetDao.load(__key);
            synchronized (this) {
                installmentPlan = installmentPlanNew;
            	installmentPlan__resolvedKey = __key;
            }
        }
        return installmentPlan;
    }

    @Generated
    public void setInstallmentPlan(InstallmentPlan installmentPlan) {
        synchronized (this) {
            this.installmentPlan = installmentPlan;
            installmentPlanId = installmentPlan == null ? null : installmentPlan.getId();
            installmentPlan__resolvedKey = installmentPlanId;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
