package in.testpress.models.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_INSTALLMENT_PLAN".
*/
public class UserInstallmentPlanDao extends AbstractDao<UserInstallmentPlan, Long> {

    public static final String TABLENAME = "USER_INSTALLMENT_PLAN";

    /**
     * Properties of entity UserInstallmentPlan.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Status = new Property(1, String.class, "status", false, "STATUS");
        public final static Property PaidInstallmentCount = new Property(2, Integer.class, "paidInstallmentCount", false, "PAID_INSTALLMENT_COUNT");
        public final static Property TotalInstallments = new Property(3, Integer.class, "totalInstallments", false, "TOTAL_INSTALLMENTS");
        public final static Property NextDueAmount = new Property(4, String.class, "nextDueAmount", false, "NEXT_DUE_AMOUNT");
        public final static Property NextDueDate = new Property(5, String.class, "nextDueDate", false, "NEXT_DUE_DATE");
        public final static Property AmountPaid = new Property(6, String.class, "amountPaid", false, "AMOUNT_PAID");
        public final static Property AmountDue = new Property(7, String.class, "amountDue", false, "AMOUNT_DUE");
        public final static Property IsCustomPlan = new Property(8, Boolean.class, "isCustomPlan", false, "IS_CUSTOM_PLAN");
        public final static Property IsPaid = new Property(9, Boolean.class, "isPaid", false, "IS_PAID");
        public final static Property IsPartiallyPaid = new Property(10, Boolean.class, "isPartiallyPaid", false, "IS_PARTIALLY_PAID");
        public final static Property IsOverdue = new Property(11, Boolean.class, "isOverdue", false, "IS_OVERDUE");
        public final static Property InstallmentPlanId = new Property(12, Long.class, "installmentPlanId", false, "INSTALLMENT_PLAN_ID");
    }

    private DaoSession daoSession;


    public UserInstallmentPlanDao(DaoConfig config) {
        super(config);
    }
    
    public UserInstallmentPlanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_INSTALLMENT_PLAN\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: id
                "\"STATUS\" TEXT," + // 1: status
                "\"PAID_INSTALLMENT_COUNT\" INTEGER," + // 2: paidInstallmentCount
                "\"TOTAL_INSTALLMENTS\" INTEGER," + // 3: totalInstallments
                "\"NEXT_DUE_AMOUNT\" TEXT," + // 4: nextDueAmount
                "\"NEXT_DUE_DATE\" TEXT," + // 5: nextDueDate
                "\"AMOUNT_PAID\" TEXT," + // 6: amountPaid
                "\"AMOUNT_DUE\" TEXT," + // 7: amountDue
                "\"IS_CUSTOM_PLAN\" INTEGER," + // 8: isCustomPlan
                "\"IS_PAID\" INTEGER," + // 9: isPaid
                "\"IS_PARTIALLY_PAID\" INTEGER," + // 10: isPartiallyPaid
                "\"IS_OVERDUE\" INTEGER," + // 11: isOverdue
                "\"INSTALLMENT_PLAN_ID\" INTEGER);"); // 12: installmentPlanId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_INSTALLMENT_PLAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserInstallmentPlan entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(2, status);
        }
 
        Integer paidInstallmentCount = entity.getPaidInstallmentCount();
        if (paidInstallmentCount != null) {
            stmt.bindLong(3, paidInstallmentCount);
        }
 
        Integer totalInstallments = entity.getTotalInstallments();
        if (totalInstallments != null) {
            stmt.bindLong(4, totalInstallments);
        }
 
        String nextDueAmount = entity.getNextDueAmount();
        if (nextDueAmount != null) {
            stmt.bindString(5, nextDueAmount);
        }
 
        String nextDueDate = entity.getNextDueDate();
        if (nextDueDate != null) {
            stmt.bindString(6, nextDueDate);
        }
 
        String amountPaid = entity.getAmountPaid();
        if (amountPaid != null) {
            stmt.bindString(7, amountPaid);
        }
 
        String amountDue = entity.getAmountDue();
        if (amountDue != null) {
            stmt.bindString(8, amountDue);
        }
 
        Boolean isCustomPlan = entity.getIsCustomPlan();
        if (isCustomPlan != null) {
            stmt.bindLong(9, isCustomPlan ? 1L: 0L);
        }
 
        Boolean isPaid = entity.getIsPaid();
        if (isPaid != null) {
            stmt.bindLong(10, isPaid ? 1L: 0L);
        }
 
        Boolean isPartiallyPaid = entity.getIsPartiallyPaid();
        if (isPartiallyPaid != null) {
            stmt.bindLong(11, isPartiallyPaid ? 1L: 0L);
        }
 
        Boolean isOverdue = entity.getIsOverdue();
        if (isOverdue != null) {
            stmt.bindLong(12, isOverdue ? 1L: 0L);
        }
 
        Long installmentPlanId = entity.getInstallmentPlanId();
        if (installmentPlanId != null) {
            stmt.bindLong(13, installmentPlanId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserInstallmentPlan entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(2, status);
        }
 
        Integer paidInstallmentCount = entity.getPaidInstallmentCount();
        if (paidInstallmentCount != null) {
            stmt.bindLong(3, paidInstallmentCount);
        }
 
        Integer totalInstallments = entity.getTotalInstallments();
        if (totalInstallments != null) {
            stmt.bindLong(4, totalInstallments);
        }
 
        String nextDueAmount = entity.getNextDueAmount();
        if (nextDueAmount != null) {
            stmt.bindString(5, nextDueAmount);
        }
 
        String nextDueDate = entity.getNextDueDate();
        if (nextDueDate != null) {
            stmt.bindString(6, nextDueDate);
        }
 
        String amountPaid = entity.getAmountPaid();
        if (amountPaid != null) {
            stmt.bindString(7, amountPaid);
        }
 
        String amountDue = entity.getAmountDue();
        if (amountDue != null) {
            stmt.bindString(8, amountDue);
        }
 
        Boolean isCustomPlan = entity.getIsCustomPlan();
        if (isCustomPlan != null) {
            stmt.bindLong(9, isCustomPlan ? 1L: 0L);
        }
 
        Boolean isPaid = entity.getIsPaid();
        if (isPaid != null) {
            stmt.bindLong(10, isPaid ? 1L: 0L);
        }
 
        Boolean isPartiallyPaid = entity.getIsPartiallyPaid();
        if (isPartiallyPaid != null) {
            stmt.bindLong(11, isPartiallyPaid ? 1L: 0L);
        }
 
        Boolean isOverdue = entity.getIsOverdue();
        if (isOverdue != null) {
            stmt.bindLong(12, isOverdue ? 1L: 0L);
        }
 
        Long installmentPlanId = entity.getInstallmentPlanId();
        if (installmentPlanId != null) {
            stmt.bindLong(13, installmentPlanId);
        }
    }

    @Override
    protected final void attachEntity(UserInstallmentPlan entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UserInstallmentPlan readEntity(Cursor cursor, int offset) {
        UserInstallmentPlan entity = new UserInstallmentPlan( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // status
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // paidInstallmentCount
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // totalInstallments
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // nextDueAmount
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // nextDueDate
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // amountPaid
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // amountDue
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0, // isCustomPlan
            cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0, // isPaid
            cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0, // isPartiallyPaid
            cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0, // isOverdue
            cursor.isNull(offset + 12) ? null : cursor.getLong(offset + 12) // installmentPlanId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserInstallmentPlan entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStatus(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPaidInstallmentCount(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setTotalInstallments(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setNextDueAmount(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setNextDueDate(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setAmountPaid(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setAmountDue(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setIsCustomPlan(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0);
        entity.setIsPaid(cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0);
        entity.setIsPartiallyPaid(cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0);
        entity.setIsOverdue(cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0);
        entity.setInstallmentPlanId(cursor.isNull(offset + 12) ? null : cursor.getLong(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserInstallmentPlan entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserInstallmentPlan entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserInstallmentPlan entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getInstallmentPlanDao().getAllColumns());
            builder.append(" FROM USER_INSTALLMENT_PLAN T");
            builder.append(" LEFT JOIN INSTALLMENT_PLAN T0 ON T.\"INSTALLMENT_PLAN_ID\"=T0.\"ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected UserInstallmentPlan loadCurrentDeep(Cursor cursor, boolean lock) {
        UserInstallmentPlan entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        InstallmentPlan installmentPlan = loadCurrentOther(daoSession.getInstallmentPlanDao(), cursor, offset);
        entity.setInstallmentPlan(installmentPlan);

        return entity;    
    }

    public UserInstallmentPlan loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<UserInstallmentPlan> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<UserInstallmentPlan> list = new ArrayList<UserInstallmentPlan>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<UserInstallmentPlan> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<UserInstallmentPlan> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
